In [3]:
import pandas as pd
import numpy as np
import re
import nltk
from collections import Counter

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\arunk\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\arunk\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\arunk\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\arunk\AppData\Roaming\nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\arunk\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.

True

In [5]:
df = pd.read_csv('imdb_dataset.csv')

In [10]:

print("***shape***")
print(df.shape)
print("***Table***")
print(df.head())
print("***headings***")
print(df.columns.tolist())

***shape***
(50000, 2)
***Table***
                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
***headings***
['review', 'sentiment']

Text to Token

In [13]:
sentence = "I love nlp and I am learning it"

In [16]:
tokens_simple = sentence.split()
print("Tokens using whitespace tokenizer:") 
print(tokens_simple)

Tokens using whitespace tokenizer:
['Hello,', 'how', 'are', 'you', 'doing', 'today?']

In [17]:
sentence = "Hello, how are you doing today?"

tokens_simple = sentence.split()
print("Tokens using whitespace tokenizer:") 
print(tokens_simple)

Tokens using whitespace tokenizer:
['Hello,', 'how', 'are', 'you', 'doing', 'today?']

In [18]:
from nltk.tokenize import word_tokenize

text = "I can't believe http://wow.com is free!!! It's amazing @user 🔥"

token_whitespace = text.split()
print("Tokens using whitespace tokenizer:")
print(token_whitespace)

Tokens using whitespace tokenizer:
['I', "can't", 'believe', 'http://wow.com', 'is', 'free!!!', "It's", 'amazing', '@user', '🔥']

In [19]:
token_nltk = word_tokenize(text)
print("\nTokens using NLTK's word_tokenize:")   
print(token_nltk)

Tokens using NLTK's word_tokenize:
['I', 'ca', "n't", 'believe', 'http', ':', '//wow.com', 'is', 'free', '!', '!', '!', 'It', "'s", 'amazing', '@', 'user', '🔥']

In [20]:
text = "I love APPLE products! Check out https://apple.com for more info. @apple #technology"

tokens_org = word_tokenize(text)
print("Original Tokens:")
print(tokens_org)

tokens_lower = word_tokenize(text.lower())
print("\nTokens after lowercasing:")
print(tokens_lower)

Original Tokens:
['I', 'love', 'APPLE', 'products', '!', 'Check', 'out', 'https', ':', '//apple.com', 'for', 'more', 'info', '.', '@', 'apple', '#', 'technology']

Tokens after lowercasing:
['i', 'love', 'apple', 'products', '!', 'check', 'out', 'https', ':', '//apple.com', 'for', 'more', 'info', '.', '@', 'apple', '#', 'technology']

In [22]:
text = "Check out my website at https://example.com! or email myemail@example.com! Price is $19.99. #exciting @user"

In [58]:

def normalize_special_tokens(text):
    
    text = re.sub(r'(https?://\S+|www\.\S+)', '<URL>', text)
    text = re.sub(r'\S+@\S+\.\S+', '<EMAIL>', text)
    text = re.sub(r'@\w+', '<MENTION>', text)
    text = re.sub(r'\b\d+(?:[.,]\d+)*\b', '<NUMBER>', text)
    return text

#df['review_special'] = df['review'].apply(normalize_special_tokens)
#df['review_special_tokens'] = df['review_special'].apply(word_tokenize)

# show examples
#print(df[['review_special', 'review_special_tokens']].head())

In [28]:
text_normalized = normalize_special_tokens(text)
print("\nText after normalizing special tokens:")
print(text_normalized)
"""tokens_normalized = word_tokenize(text_normalized)   
print("\nTokens after normalizing special tokens:")
print(tokens_normalized)"""

Text after normalizing special tokens:
Check out my website at <URL> or email <EMAIL> Price is $<NUMBER>. #exciting <MENTION>

'tokens_normalized = word_tokenize(text_normalized)   \nprint("\nTokens after normalizing special tokens:")\nprint(tokens_normalized)'

Remove Stopwords and keep Negation

In [37]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

In [38]:
print("\nStopwords in English:")
print(stop_words)

Stopwords in English:
{'the', 'mustn', 'because', 'not', 'wouldn', 'once', "we've", 'each', 'o', 'has', 'further', "we'd", 'if', "haven't", "it'd", 'through', 'such', 'their', "shouldn't", 'wasn', 'shouldn', 'some', "mustn't", 'doing', 'will', 'ain', 'as', 'during', 'won', "they're", "doesn't", 'above', 'nor', 'itself', 'with', "isn't", 'himself', 'over', "wasn't", "mightn't", 'he', 'i', 'don', "couldn't", 'is', 'hadn', 'other', 'more', "they'll", 'any', 'an', "she'd", 'mightn', "won't", 'ourselves', "she's", 'yours', 'from', 'few', "he's", 'these', "shan't", 'can', 'my', 'be', 'was', 'own', "hadn't", 'have', 'him', "i'd", 'his', "i'll", 'both', 'most', 'needn', "weren't", 'am', 'doesn', "it's", 'so', 'do', 'you', 'than', "you've", 's', "aren't", 'why', 'those', 'down', 'her', 'myself', 'having', 'about', "should've", 't', "that'll", 'below', 'should', 'ma', "they'd", 'at', 'just', 've', 'a', 'into', "needn't", 'of', 'were', "you'd", 'or', 'yourself', 'yourselves', 'when', 'who', 'themselves', 'ours', 'been', 'what', 'between', 'did', 'no', 'same', 'but', "hasn't", 'all', 'now', 'm', 'until', 'very', 're', 'isn', "she'll", 'she', "i've", 'where', "don't", 'our', 'are', 'on', 'again', 'hers', 'your', "you'll", "didn't", 'had', 'didn', "he'd", 'that', "he'll", 'y', 'after', 'weren', 'couldn', "they've", 'being', 'up', 'they', 'out', "wouldn't", "you're", 'haven', 'under', 'whom', "it'll", 'shan', 'to', 'it', 'and', 'there', 'which', 'before', 'hasn', 'by', 'then', 'only', 'll', "we're", 'how', 'me', 'in', 'herself', 'd', 'theirs', 'aren', 'does', 'them', 'this', 'its', "i'm", 'while', "we'll", 'off', 'too', 'for', 'here', 'we', 'against'}

In [39]:
negation_words = ["not", "no", "never", "n't", "cannot", "can't", "don't", "doesn't", "didn't", "won't", "wouldn't", "shouldn't", "couldn't", "isn't", "aren't", "wasn't", "weren't", "haven't", "hasn't", "hadn't"]

In [40]:
for word in negation_words:
    if word in stop_words:
        print(f"❌ Negation word '{word}' is in the stopwords list.")
        stop_words.remove(word)
    else:
        print(f"✅ Negation word '{word}' is NOT in the stopwords list.")

❌ Negation word 'not' is in the stopwords list.
❌ Negation word 'no' is in the stopwords list.
✅ Negation word 'never' is NOT in the stopwords list.
✅ Negation word 'n't' is NOT in the stopwords list.
✅ Negation word 'cannot' is NOT in the stopwords list.
✅ Negation word 'can't' is NOT in the stopwords list.
❌ Negation word 'don't' is in the stopwords list.
❌ Negation word 'doesn't' is in the stopwords list.
❌ Negation word 'didn't' is in the stopwords list.
❌ Negation word 'won't' is in the stopwords list.
❌ Negation word 'wouldn't' is in the stopwords list.
❌ Negation word 'shouldn't' is in the stopwords list.
❌ Negation word 'couldn't' is in the stopwords list.
❌ Negation word 'isn't' is in the stopwords list.
❌ Negation word 'aren't' is in the stopwords list.
❌ Negation word 'wasn't' is in the stopwords list.
❌ Negation word 'weren't' is in the stopwords list.
❌ Negation word 'haven't' is in the stopwords list.
❌ Negation word 'hasn't' is in the stopwords list.
❌ Negation word 'hadn't' is in the stopwords list.

In [41]:
sentence = "I don't like this movie at all."

tokens = word_tokenize(sentence)
print("Tokens before removing stopwords:")
print(tokens)
tokens_no_stopwords = [word for word in tokens if word.lower() not in stop_words]
print("\nTokens after removing stopwords:")
print(tokens_no_stopwords)

Tokens before removing stopwords:
['I', 'do', "n't", 'like', 'this', 'movie', 'at', 'all', '.']

Tokens after removing stopwords:
["n't", 'like', 'movie', '.']

Punctuations

In [42]:
exmaples = ["This movie is not good at all!", 
            "I have never seen such a bad film.", 
            "The plot was terrible and I don't recommend it.",
            "I can't say this movie is worth watching."
            "That's great!!!"]

In [44]:
import string

def remove_punctuation(text,keep_important=True):
    if keep_important:
        #Keep '!' and '?' as they can carry sentiment information
        punctuation_to_remove = string.punctuation.replace('!', '').replace('?', '')
    else:
        punctuation_to_remove = string.punctuation
    return text.translate(str.maketrans('', '', punctuation_to_remove))

In [48]:
sentence = "Wow!!! This movie is amazing, I can't believe it..."

print("Original sentence:")
print(sentence)

print("\nSentence after removing all punctuation:")
print(remove_punctuation(sentence, keep_important=False))

print("\nSentence after removing punctuation (keeping '!' and '?'):")
print(remove_punctuation(sentence, keep_important=True))

Original sentence:
Wow!!! This movie is amazing, I can't believe it...

Sentence after removing all punctuation:
Wow This movie is amazing I cant believe it

Sentence after removing punctuation (keeping '!' and '?'):
Wow!!! This movie is amazing I cant believe it

Stemming & Lemmatization

In [53]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

words = ["running", "ran", "runs", "easily", "fairly", "better", "best", "happier", "happiest", "studies", "studying", "studied","wolves","feet"]

for word in words:
    print(f"Original: {word:10} | Stemmed: {stemmer.stem(word):10} | Lemmatized: {lemmatizer.lemmatize(word):10}")

Original: running    | Stemmed: run        | Lemmatized: running
Original: ran        | Stemmed: ran        | Lemmatized: ran
Original: runs       | Stemmed: run        | Lemmatized: run
Original: easily     | Stemmed: easili     | Lemmatized: easily
Original: fairly     | Stemmed: fairli     | Lemmatized: fairly
Original: better     | Stemmed: better     | Lemmatized: better
Original: best       | Stemmed: best       | Lemmatized: best
Original: happier    | Stemmed: happier    | Lemmatized: happier
Original: happiest   | Stemmed: happiest   | Lemmatized: happiest
Original: studies    | Stemmed: studi      | Lemmatized: study
Original: studying   | Stemmed: studi      | Lemmatized: studying
Original: studied    | Stemmed: studi      | Lemmatized: studied
Original: wolves     | Stemmed: wolv       | Lemmatized: wolf
Original: feet       | Stemmed: feet       | Lemmatized: foot

In [87]:
def preprocess_text(text,
                    lowercase=True,
                    normalize=True,
                    remove_stopwords=True,
                    perserve_negation=True,
                    stem=False,
                    lemmatize=False):
    
    if normalize:
        text = re.sub(r'(https?://\S+|www\.\S+)', ' ', text)
        text = re.sub(r'\S+@\S+\.\S+', ' ', text)
        text = re.sub(r'<[^>]+>', ' ', text) # Remove HTML tags

    if lowercase:
        text = text.lower()

    tokens = word_tokenize(text)

    if remove_stopwords:
        stop_words = set(stopwords.words('english'))
        if perserve_negation:
            negation_words = ["not", "no", "never", "n't", "cannot", "can't", "don't", "doesn't", "didn't", "won't", "wouldn't", "shouldn't", "couldn't", "isn't", "aren't", "wasn't", "weren't", "haven't", "hasn't", "hadn't"]
            stop_words = stop_words - set(negation_words)
        tokens = [word for word in tokens if word not in stop_words]    
    
    tokens = [t for t in tokens if t.isalpha() or t == "n't"]
        
    if stem:
        stemmer = PorterStemmer()
        tokens = [stemmer.stem(word) for word in tokens]

    if lemmatize:
        lemmatizer = WordNetLemmatizer()
        tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return tokens

In [88]:
sample_text = df['review'].iloc[0]
print("Original Text:") 
print(sample_text)

token_basic = preprocess_text(sample_text)
print("\nPreprocessed Text (Basic):")
print(token_basic[:20])  # Print first 20 tokens after basic preprocessing

token_stemmed = preprocess_text(sample_text, lowercase=True, remove_stopwords=True, perserve_negation=True, stem=True, lemmatize=False)
print("\nPreprocessed Text with Stemming:")
print(token_stemmed[:20])  # Print first 20 tokens after stemming

token_lemmatized = preprocess_text(sample_text, lowercase=True, remove_stopwords=True, perserve_negation=True, stem=False, lemmatize=True)
print("\nPreprocessed Text with Lemmatization:")
print(token_lemmatized)

"""token = word_tokenize(preprocessed_text)
print("Tokens after preprocessing:")
print(token)"""

Original Text:
One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

Preprocessed Text (Basic):
['one', 'reviewers', 'mentioned', 'watching', 'oz', 'episode', 'hooked', 'right', 'exactly', 'happened', 'first', 'thing', 'struck', 'oz', 'brutality', 'unflinching', 'scenes', 'violence', 'set', 'right']

Preprocessed Text with Stemming:
['one', 'review', 'mention', 'watch', 'oz', 'episod', 'hook', 'right', 'exactli', 'happen', 'first', 'thing', 'struck', 'oz', 'brutal', 'unflinch', 'scene', 'violenc', 'set', 'right']

Preprocessed Text with Lemmatization:
['one', 'reviewer', 'mentioned', 'watching', 'oz', 'episode', 'hooked', 'right', 'exactly', 'happened', 'first', 'thing', 'struck', 'oz', 'brutality', 'unflinching', 'scene', 'violence', 'set', 'right', 'word', 'go', 'trust', 'not', 'show', 'faint', 'hearted', 'timid', 'show', 'pull', 'no', 'punch', 'regard', 'drug', 'sex', 'violence', 'hardcore', 'classic', 'use', 'word', 'called', 'oz', 'nickname', 'given', 'oswald', 'maximum', 'security', 'state', 'penitentary', 'focus', 'mainly', 'emerald', 'city', 'experimental', 'section', 'prison', 'cell', 'glass', 'front', 'face', 'inwards', 'privacy', 'not', 'high', 'agenda', 'em', 'city', 'home', 'many', 'aryan', 'muslim', 'gangsta', 'latino', 'christian', 'italian', 'irish', 'scuffle', 'death', 'stare', 'dodgy', 'dealing', 'shady', 'agreement', 'never', 'far', 'away', 'would', 'say', 'main', 'appeal', 'show', 'due', 'fact', 'go', 'show', 'would', "n't", 'dare', 'forget', 'pretty', 'picture', 'painted', 'mainstream', 'audience', 'forget', 'charm', 'forget', 'romance', 'oz', "n't", 'mess', 'around', 'first', 'episode', 'ever', 'saw', 'struck', 'nasty', 'surreal', 'could', "n't", 'say', 'ready', 'watched', 'developed', 'taste', 'oz', 'got', 'accustomed', 'high', 'level', 'graphic', 'violence', 'not', 'violence', 'injustice', 'crooked', 'guard', 'sold', 'nickel', 'inmate', 'kill', 'order', 'get', 'away', 'well', 'mannered', 'middle', 'class', 'inmate', 'turned', 'prison', 'bitch', 'due', 'lack', 'street', 'skill', 'prison', 'experience', 'watching', 'oz', 'may', 'become', 'comfortable', 'uncomfortable', 'viewing', 'thats', 'get', 'touch', 'darker', 'side']

'token = word_tokenize(preprocessed_text)\nprint("Tokens after preprocessing:")\nprint(token)'

In [101]:
df['tokens'] = df['review'].apply(lambda x: preprocess_text(x, normalize=True, lowercase=True, remove_stopwords=True, perserve_negation=True, stem=False, lemmatize=True))

In [103]:
df = df.drop('preprocessed_review_tokens', axis=1)

In [104]:
df.head()

,review,sentiment,tokens
0,One of the other reviewers has mentioned that ...,positive,"[one, reviewer, mentioned, watching, oz, episo..."
1,A wonderful little production. <br /><br />The...,positive,"[wonderful, little, production, filming, techn..."
2,I thought this was a wonderful way to spend ti...,positive,"[thought, wonderful, way, spend, time, hot, su..."
3,Basically there's a family where a little boy ...,negative,"[basically, family, little, boy, jake, think, ..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"[petter, mattei, love, time, money, visually, ..."

Processing Tokens

Bow

In [105]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()

In [106]:
def clean_text(text):
    
    text = re.sub(r'<[^>]+>', '', text)  # Remove HTML tags
    text = text.lower()  # Convert to lowercase
    return text

In [107]:
df['clean_text'] = df['review'].apply(clean_text)

In [108]:
df.head()

,review,sentiment,tokens,clean_text
0,One of the other reviewers has mentioned that ...,positive,"[one, reviewer, mentioned, watching, oz, episo...",one of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,positive,"[wonderful, little, production, filming, techn...",a wonderful little production. the filming tec...
2,I thought this was a wonderful way to spend ti...,positive,"[thought, wonderful, way, spend, time, hot, su...",i thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,negative,"[basically, family, little, boy, jake, think, ...",basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"[petter, mattei, love, time, money, visually, ...","petter mattei's ""love in the time of money"" is..."

In [115]:
vectorizer = CountVectorizer(max_features=1000, stop_words='english')

X_bow = vectorizer.fit_transform(df['clean_text'])

In [116]:
print("Shape of BoW feature matrix:", X_bow.shape)
print("Sample feature names:", vectorizer.get_feature_names_out()[:20])
print("Sample BoW vector for first review:")
print(X_bow[0].toarray())

Shape of BoW feature matrix: (50000, 1000)
Sample feature names: ['10' '100' '15' '20' '30' '50' '80' '90' 'ability' 'able' 'absolutely'
 'accent' 'act' 'acted' 'acting' 'action' 'actor' 'actors' 'actress'
 'actual']
Sample BoW vector for first review:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2
  1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 3 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2
  0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 2 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

In [117]:
print(f"{X_bow.shape[0]} documents and {X_bow.shape[1]} features.")

50000 documents and 1000 features.

In [119]:
word_counts = X_bow.sum(axis=0).A1
word_freq = list(zip(vectorizer.get_feature_names_out(), word_counts))
word_freq.sort(key=lambda x: x[1], reverse=True)

print("Top 20 most common words:") 
for word, count in word_freq[:20]:
    print(f"{word}: {count}")

Top 20 most common words:
movie: 87934
film: 79672
like: 40160
just: 35169
good: 29737
time: 25099
story: 23108
really: 23089
bad: 18461
people: 18182
great: 18136
don: 17616
make: 15891
way: 15644
movies: 15301
characters: 14444
think: 14334
watch: 13941
character: 13900
films: 13752

In [ ]:
positive_reviews = df['sentiment'] == 'positive'
negative_reviews = df['sentiment'] == 'negative'

positive_count = X_bow[positive_reviews.values].sum(axis=0).A1
negative_count = X_bow[negative_reviews.values].sum(axis=0).A1

In [114]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(
    max_features=1000, 
    stop_words='english',
    ngram_range=(1,2))

X_tidf = tfidf_vectorizer.fit_transform(df['clean_text'])

In [120]:
print(f"TF-IDF feature matrix shape: {X_tidf.shape}")
print(f" {X_tidf.shape[0]} documents and {X_tidf.shape[1]} features.")

TF-IDF feature matrix shape: (50000, 1000)
 50000 documents and 1000 features.

In [121]:
idf_scores = tfidf_vectorizer.idf_
feature_names = tfidf_vectorizer.get_feature_names_out()

In [122]:
idf_df = pd.DataFrame({'feature': feature_names, 'idf_score': idf_scores})
idf_df = idf_df.sort_values(by='idf_score', ascending=False)

print("Top 20 features with highest IDF scores:")
print(idf_df.head(20))

print("Top 20 features with lowest IDF scores:")
print(idf_df.tail(20))

Top 20 features with highest IDF scores:
       feature  idf_score
921    vampire   5.625393
447       jane   5.522689
999     zombie   5.499030
137  christmas   5.432919
28       alien   5.416224
75         ben   5.391693
539      match   5.374078
671     prison   5.369328
618       park   5.314014
109       camp   5.290379
808      south   5.284557
749      scott   5.283107
129    charles   5.277326
347       gang   5.271579
117        cat   5.255943
922        van   5.253126
889      train   5.251720
62        band   5.248915
43        army   5.230872
113    cartoon   5.222653
Top 20 features with lowest IDF scores:
        feature  idf_score
128  characters   2.585253
757        seen   2.543015
13       acting   2.542454
575      movies   2.537975
873       think   2.535371
948       watch   2.522822
59          bad   2.445046
954         way   2.441827
528        make   2.408069
627      people   2.402200
372       great   2.380491
228         don   2.349558
830       story   2.213101
696      really   2.200864
877        time   2.059546
368        good   1.967551
454        just   1.868140
495        like   1.769573
317        film   1.588447
571       movie   1.492253

In [129]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X_tidf, df['sentiment'], test_size=0.2, random_state=42)

In [130]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(x_train, y_train)

model.score(x_test, y_test)

0.8659